import type { AnalysisResult } from "./llm";

function scoreColorHex(score: number): string {
  if (score >= 90) return "#34d399";
  if (score >= 80) return "#4ade80";
  if (score >= 70) return "#facc15";
  if (score >= 60) return "#fb923c";
  return "#f87171";
}

function statusEmoji(status: string): string {
  if (status === "pass") return "\u2705";
  if (status === "warning") return "\u26A0\uFE0F";
  return "\u274C";
}

/**
 * Generate a standalone HTML report that can be saved as a file or printed to PDF.
 */
export function exportAsHtml(result: AnalysisResult): string {
  const color = scoreColorHex(result.overall_score);
  const dims = result.dimensions
    .map(
      (dim) => `
    <div style="border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:16px;">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
        <h3 style="margin:0;font-size:16px;">${statusEmoji(dim.status)} ${dim.name}</h3>
        <span style="color:${scoreColorHex(dim.score * 10)};font-weight:700;font-size:14px;">${dim.score}/10</span>
      </div>
      ${dim.issues.length ? `<div style="margin-bottom:8px;"><strong style="font-size:13px;color:#64748b;">Issues</strong><ul style="margin:4px 0 0 0;padding-left:20px;">${dim.issues.map((i) => `<li style="font-size:14px;margin-bottom:4px;">${escapeHtml(i)}</li>`).join("")}</ul></div>` : ""}
      ${dim.suggestions.length ? `<div style="margin-bottom:8px;"><strong style="font-size:13px;color:#64748b;">Suggestions</strong><ul style="margin:4px 0 0 0;padding-left:20px;">${dim.suggestions.map((s) => `<li style="font-size:14px;margin-bottom:4px;">${escapeHtml(s)}</li>`).join("")}</ul></div>` : ""}
      ${dim.rewrite_example ? `<div><strong style="font-size:13px;color:#64748b;">Rewrite Example</strong><blockquote style="margin:4px 0 0 16px;padding:8px 12px;border-left:3px solid ${color};font-size:14px;color:#475569;">${escapeHtml(dim.rewrite_example)}</blockquote></div>` : ""}
    </div>`
    )
    .join("");

  const shipBadge = result.ship_recommendation
    ? `<div style="text-align:center;margin-top:12px;">
        <span style="display:inline-block;padding:4px 14px;border-radius:8px;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;
          ${result.ship_recommendation === "ship" ? "background:#d1fae5;color:#059669;" : result.ship_recommendation === "revise" ? "background:#fef3c7;color:#d97706;" : "background:#fee2e2;color:#dc2626;"}">
          ${result.ship_recommendation === "ship" ? "Ship It" : result.ship_recommendation === "revise" ? "Revise" : "Reject"}
        </span>
        ${result.ship_rationale ? `<p style="margin-top:8px;font-size:13px;color:#64748b;">${escapeHtml(result.ship_rationale)}</p>` : ""}
      </div>`
    : "";

  const growthSection = result.growth_focus
    ? `<div style="border:2px solid ${color};border-radius:12px;padding:20px;margin-top:16px;">
        <h3 style="margin:0 0 12px 0;font-size:16px;">Growth Focus</h3>
        <p style="font-size:14px;"><strong>Skill:</strong> ${escapeHtml(result.growth_focus.skill)}</p>
        <p style="font-size:14px;"><strong>Diagnosis:</strong> ${escapeHtml(result.growth_focus.diagnosis)}</p>
        <p style="font-size:14px;"><strong>Recommendation:</strong> ${escapeHtml(result.growth_focus.recommendation)}</p>
      </div>`
    : "";

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>PRD Linter Report — Score ${result.overall_score}/100</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #0f172a; line-height: 1.6; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
  <div style="text-align:center;margin-bottom:32px;">
    <h1 style="margin:0;font-size:24px;">PRD Linter Report</h1>
    ${result.persona ? `<p style="margin:4px 0 0;font-size:13px;color:#64748b;">Reviewed as: ${escapeHtml(result.persona)}</p>` : ""}
    <div style="margin:20px 0;">
      <span style="display:inline-block;font-size:48px;font-weight:800;color:${color};">${result.overall_score}</span>
      <span style="font-size:20px;color:#94a3b8;">/100</span>
    </div>
    <p style="font-size:15px;color:#475569;max-width:500px;margin:0 auto;">${escapeHtml(result.overall_verdict)}</p>
    ${shipBadge}
  </div>

  ${dims}
  ${growthSection}

  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center;">
    <p style="font-size:12px;color:#94a3b8;">Generated by <a href="https://github.com/sohaibt/prdlinter" style="color:#6366f1;">PRD Linter</a> by <a href="https://masteringproducthq.com" style="color:#6366f1;">Mastering Product HQ</a></p>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Trigger a browser download of the HTML report.
 */
export function downloadHtmlReport(result: AnalysisResult): void {
  const html = exportAsHtml(result);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `prd-report-${result.overall_score}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAsMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push("# PRD Linter Report");
  lines.push("");
  if (result.persona) {
    lines.push(`**Reviewer:** ${result.persona}`);
  }
  lines.push(`**Overall Score:** ${result.overall_score}/100`);
  lines.push(`**Verdict:** ${result.overall_verdict}`);
  if (result.ship_recommendation) {
    const badge =
      result.ship_recommendation === "ship"
        ? "SHIP"
        : result.ship_recommendation === "revise"
          ? "REVISE"
          : "REJECT";
    lines.push(`**Recommendation:** ${badge}`);
    if (result.ship_rationale) {
      lines.push(`**Rationale:** ${result.ship_rationale}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const dim of result.dimensions) {
    const statusEmoji =
      dim.status === "pass" ? "\u2705" : dim.status === "warning" ? "\u26A0\uFE0F" : "\u274C";
    lines.push(`## ${statusEmoji} ${dim.name} \u2014 ${dim.score}/10 (${dim.status})`);
    lines.push("");

    if (dim.issues.length > 0) {
      lines.push("### Issues");
      for (const issue of dim.issues) {
        lines.push(`- ${issue}`);
      }
      lines.push("");
    }

    if (dim.suggestions.length > 0) {
      lines.push("### Suggestions");
      for (const suggestion of dim.suggestions) {
        lines.push(`- ${suggestion}`);
      }
      lines.push("");
    }

    if (dim.rewrite_example) {
      lines.push("### Rewrite Example");
      lines.push("");
      lines.push(`> ${dim.rewrite_example}`);
      lines.push("");
    }

    if (dim.issues.length === 0 && dim.suggestions.length === 0 && !dim.rewrite_example) {
      lines.push("No issues found.");
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  if (result.growth_focus) {
    lines.push("## \u{1F3AF} Growth Focus");
    lines.push("");
    lines.push(`**Skill to develop:** ${result.growth_focus.skill}`);
    lines.push("");
    lines.push(`**Diagnosis:** ${result.growth_focus.diagnosis}`);
    lines.push("");
    lines.push(`**Recommendation:** ${result.growth_focus.recommendation}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by [PRD Linter](https://github.com/your-username/prdlinter)*");

  return lines.join("\n");
}
