import type { AnalysisResult } from "./llm";

export function exportAsMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push("# PRD Linter Report");
  lines.push("");
  lines.push(`**Overall Score:** ${result.overall_score}/100`);
  lines.push(`**Verdict:** ${result.overall_verdict}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const dim of result.dimensions) {
    const statusEmoji =
      dim.status === "pass" ? "✅" : dim.status === "warning" ? "⚠️" : "❌";
    lines.push(`## ${statusEmoji} ${dim.name} — ${dim.score}/10 (${dim.status})`);
    lines.push("");

    if (dim.issues.length > 0) {
      lines.push("### Issues");
      for (const issue of dim.issues) {
        lines.push(`- ${issue}`);
      }
      lines.push("");
    }

    if (dim.suggestions.length > 0) {
      lines.push("### Suggestions");
      for (const suggestion of dim.suggestions) {
        lines.push(`- ${suggestion}`);
      }
      lines.push("");
    }

    if (dim.issues.length === 0 && dim.suggestions.length === 0) {
      lines.push("No issues found.");
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by [PRD Linter](https://github.com/your-username/prdlinter)*");

  return lines.join("\n");
}
